declare var define: any;

define([], (): IM365LPStrings => {
  return {
    WebpartTitleLabel: "Web Dels Titel (Bara innehålls läge)",
    LPViewerPropertyDescription: "Custom Learning Egenskaper",
    LPViewerPropertyGroupName: "Standard vy",
    WebpartModeLabel: "Välj Web Part läge",
    WebpartModeDescription: "Hur vill du visa webparten",
    ShowNavigationLabel: "Visa Anpassad Läro Navigerings Rubrik",
    DefaultFilterLabel: "Välj ett filter",
    DefaultFilterDescription: "Välj ett filter för att begränsa resultaten. Du kan bara filtrera på en typ åt gången.",
    DefaultCategoryLabel: "Filtrera till kategorin",
    DefaultCategoryDescription: "Välj en kategori för att begränsa resultat.",
    DefaultSubCategoryLabel: "Filtrera till underkategori",
    DefaultSubCategoryDescription: "Välj en underkategori för att begränsa resultat.",
    DefaultPlaylistLabel: "Filtrera till spellista",
    DefaultPlaylistDescription: "Välj en kategori för att begränsa resultat.",
    DefaultAssetLabel: "Välj en tillgång",
    DefaultAssetDescription: "Välj en tillgång som ska visas från spellistan.",
    FilterPanelHeader: "Välj de kurser som passar dig bäst",
    FilterPanelAudienceLabel: "Jag är en",
    FilterPanelSkillsetLabel: "Min skicklighet är",
    NavigationHome: "Hem",
    SearchResultItemPlayListLabel: "Spellista: ",
    SearchResultItemCategoryLabel: "Kategori:",
    SearchPanelPlaceHolderLabel: "Sök efter spellistor eller tillgångar",
    LinkPanelCopyLabel: "Kopiera",
    HeaderPlaylistPanelCurrentPlaylistLabel: "Aktuell spellista:",
    HeaderPlaylistPanelAdminHeader: "Administrering",
    PlaylistOverviewDesignMessage: "Under användning kommer detta område att visa andra tillgångar i spellistan som den visas i.",
    PlaylistOverviewHeading: "Alla steg i spellista",
    BurgerButton: "burger",
    LinkButton: "Länk",
    SearchButton: "Sök",
    AdministerPlaylist: "Spellista administration",
    NoSearchResults: "Inga sökresultat matchade din fråga.",
    DefaultCDNLabel: "Välj inlärningskälla",
    DefaultCDNDescription: "Välj alternativ källa för inlärningsinnehåll.",
    DescriptionFieldLabel: "Beskrivning fält",
    ImageSelectorLabel: "Välj en bild",
    ImageSelectorButton: "Välj bild",
    DetailEditTitle: "Titel",
    DetailEditDescription: "Beskrivning",
    DetailEditUrl: "Url",
    DetailEditCategory: "Kategori",
    DetailEditCategoryNoData: "Inga kategorier är tillgängliga",
    DetailEditTechnology: "Teknologi",
    DetailEditLevel: "Nivå",
    DetailEditAudience: "Publik",
    AssetSearchPlaceHolderLabel: "Sök efter befintliga tillgångar",
    CategoryHeading: "Lägg till ny underkategori",
    CategoryHeadingLabel: "Underkategori",
    CategoryPlaylistSavedMessage: "Spellistan sparades!",
    CategoryPlaylistSaveFailedMessage: "Misslyckades med att spara spellista!",
    CategoryNewPlayListMessage: "Du har gjort ändringar i en ny spellista. Vill du kassera dina ändringar och fortsätta?",
    CategoryEditedPlayListMessage: "Du har gjort ändringar i den här spellistan. Vill du kassera dina ändringar och fortsätta?",
    PlaylistEditAssetSavedMessage: "Tillgången sparades!",
    PlaylistEditAssetSaveFailedMessage: "Misslyckades med att spara tillgång!",
    PlaylistEditCreatePlaylistHeader: "Skapa en ny spellista",
    PlaylistEditPlaylistDetailsHeader: "Spellista detaljer:",
    PlaylistEditPlaylistAssetsHeader: "Spellista tillgångar",
    PlaylistEditEditLabel: "Redigera detaljer",
    PlaylistEditSaveLabel: "Spara detaljer",
    PlaylistEditCancelLabel: "Avbryt detalj",
    PlaylistEditCloseLabel: "Stäng spellista",
    AssetDetailsCreateHeader: "Skapa en ny tillgång",
    AssetDetailsManageHeader: "Hantera anpassad tillgång:",
    AssetDetailsDetailsHeader: "Tillgångs Detaljer:",
    AssetDetailsSaveLabel: "Spara tillgång",
    AssetDetailsCancelLabel: "Avbryt tillgång",
    AssetDetailsCloseLabel: "Stäng tillgång",
    AssetDetailsOpenPage: "Öppna sidan",
    TechnologyHeadingLabel: "Teknologi",
    SubcategoryHeadingLabel: "Underkategori rubrik",
    PlaylistItemPlaylistHeadingLabel: "Spellista",
    PlaylistItemPlaylistDelete: "Radera spellista",
    PlaylistEditAssetNewLabel: "Ny tillgång",
    PlaylistRemove: "Ta bort från spellista",
    ImageSelectorImageAlt: "Anpassad spellista",
    ImageSelectorUrlPlaceholder: "Bild URL",
    CategoryHeadingAddPlaylistToSubcategory: "Lägg till ny spellista till underkategori",
    AdminMenuTechnologyLabel: "Teknologi",
    AdminMenuCategoryLabel: "Kategori",
    Show: "show",
    Hide: "Dölj",
    Add: "Lägg till",
    Edit: "Redigera",
    CloseButton: "Stänga",
    EditButton: "Redigera",
    StepButton: "Steg",
    MoveUpButton: "Flytta upp",
    MoveDownButton: "Flytta ner",
    SaveButton: "Spara",
    CancelButton: "Avbryt",
    UpdateButton: "Uppdatering",
    DeleteButton: "Radera",
    DetailEditNewPageMessage: "Ny tillgångssida på webbplatsens sidor.",
    DetailEditExistingPageMessage: "Ange webbadressen till en befintlig sida.",
    DetailEditNewPageButton: "Skapa tillgångssida",
    DetailEditExistingPageButton: "Skriv in URL",
    AdminAddCdnLabel: "Lägg till innehållspaket",
    AdminEditCdnLabel: "Redigera innehållspaket",
    AdminDeleteCdnLabel: "Radera innehållspaket",
    AdminCdnIdLabel: "Content Pack ID / Partner ID",
    AdminCdnDisplayName: "Visa namn",
    AdminCdnBaseUrl: "baseUrl",
    AdminCustomCdnTitle: "customContentPack",
    AdminCustomCdnDescription: "Anpassade innehållspaket är en avancerad funktion och bör endast användas av administratörer med erfarenhet av att administrera webbinnehåll. Untrustworthy content källor kan introducera osäkert innehåll på din webbplats. Du bör bara lägga till källor som du litar på. För mer information, se Partner Guidance iLärande vägar dokumentation. ",
    AdminConfirmContentPack: "En ny webbläsarflik har startats som gör att du kan tillhandahålla det nya innehållspaketet. När du har gjort det, klicka på  slutför nedan för att uppdatera alternativet Alternativt innehåll. Om du har ett fel eller väljer att inte installera innehålletPack, klicka på Avbryt, du kan komma tillbaka när som helst. ",
    AdminCdnCompleteButton: "Komplett",
    AdminCdnCancelButton: "Avbryt",
    AdminCdnSaveButton: "Spara",
    AdminCdnUpdateButton: "Uppdatering",
    AdminRemoveCdn: "Vänligen bekräfta att du vill ta bort den valda CDN?",
    AdminAbout: "Om webbdel",
    DocumentationLinkLabel: "Öppna M365 Learning Pathways dokumentation",
    CategoryCopyPlaylistFail: "Misslyckad kopieringspellista, vänligen kontakta administratören eller se webbläsarkonsolen för mer information.",
    PlaylistEditCopyLabel: "Kopiera spellista",
    PlaylistNext: "Nästa",
    PlaylistPrevious: "Tidigare",
    PlaylistFullScreen: "Växla helskärmsläge",
    FilterNotSet: "Allt",
    AdminVersionUpdateNotice: "Din installerade Microsoft 365 Learning Pathways webbdel är föråldrad. Du kör för närvarande version% 0% och den nyaste versionen är% 1%.",
    AdminVersionUpdateInstructions: "Kolla in instruktionerna för Uppdatera lösningen.",
    AdminSecurityMessage: "Du har inte rätt att administrera Microsoft 365 Learning Pathways. Vänligen prata med administratören om att gå med i ägarna eller medlemmarna.",
    AdminConfigIssueMessage: "Microsoft 365 Learning Pathways har ett konfigurationsfel. Fråga din administratör för hjälp. [Administratörer: Vänligen se webbläsarkonsolen för detaljerade loggar. För teknisk assistans kolla in problemlistan på https://github.com/pnp/custom-learning-Office-365 / Problem.] ",
    AdminAwaitingUrlPrompt: "URL: Väntar på titel ...",
    CreatingPage: "Skapa sidan",
    TryAgain: "Försök igen",
    AddLanguagePlaceholder: "Lägg till språk",
    NotApplicable: "Inte tillämpbar",
    DataUpgradeTitle: "Datauppgradering från",
    DataUpgradeIntro: "Du har uppdaterat till en stor ny release av Microsoft 365 Learning Pathways. För att starta uppgraderingsprocessen trycker du på 'Start'",
    DataUpgradeStart: "start",
    DataUpgradeClose: "Stänga",
    DataUpgradeIssue: "Om du stöter på problem som utför uppdateringen kan du begära hjälp genom att skicka ett problem till",
    DataUpgradeIssueLink: "Microsoft 365 Learning Pathways GitHub Problemlista.",
    DataUpgradeLog: "Uppgradera logg",
    DataUpgradeComplete: "Uppgraderingen har slutfört.",
    DataUpgradeErrors: "Fel",
    LogLevel: "Nivå",
    LogMessage: "Meddelande",
    AboutGroupHeader: "M365 Learning Pathways",
    AboutGroupTitle: "Aktuell konfiguration *",
    AboutGroupTitle2: "(* kommer att vara aktuellt innehållspaket specifikt)",
    AboutLearningSiteUrl: "Lärande webbplatsadress:",
    AboutBaseCDNPath: "Base CDN-sökväg:",
    AboutTelemetryStatus: "Telemetry status:",
    AboutCurrentWPVersion: "Aktuell webbdelversion:",
    AboutMultilingualEnabled: "Flerspråkiga sidor aktiverade:",
    AboutMultilingualLanguages: "Flerspråkiga sidor översättningsspråk:",
    AboutConfiguredLanguages: "Konfigurerade språk:",
    AboutSupportedLanguages: "Innehållspaket stödda språk:",
    AboutDefaultSiteLanguage: "Standard webbplats språk:",
    AboutCurrentUserLanguage: "Aktuellt användarspråk:",
    AboutContentPackAssetOrigins: "contentPackAssetOrigins:",
    AboutCurrentCDN: "Aktuell CDN:",
    AboutAllCDNs: "Alla cdns:",
    AboutCacheLastUpdate: "Cache senast uppdatering:",
    DocumentLibraries: "Dokumentbibliotek",
    OpenButtonLabel: "Öppen",
    CancelButtonLabel: "Avbryt",
    UploadFileHeader: "Ladda upp fil",
    ChangeFileLinkLabel: "Ändra fil",
    ChooseFileLinkLabel: "Välj FIL",
    AddFileButtonLabel: "Lägg till fil",
    WebSearchLinkLabel: "Webbsökning",
    CreativeCommonsMessage: "Dessa resultat är taggade med Creative Commons licenser. Granska licenserna för att säkerställa att du följer.",
    CopyrightWarning: "Du är ansvarig för att respektera andras rättigheter, inklusive upphovsrätt.",
    CopyrightUrl: "https://www.microsoft.com/en-US/legal/copyright/default.aspx",
    LearnMoreLink: "Läs mer.",
    NoResultsBadEnglish: "*** Det finns inget resultat. Försök ändra filteralternativen",
    SearchResultAlt: "Bildresultat för {0}.",
    SearchResultAriaLabel: "Tryck på ENTER för att öppna bildkällan på en ny flik.",
    SearchBoxPlaceholder: "Webbsökning",
    PoweredByBing: "Drivs av Bing",
    SizeOptionAll: "Allt",
    SizeOptionExtraLarge: "Extra stor",
    SizeOptionLarge: "Stor",
    SizeOptionMedium: "medium",
    SizeOptionSmall: "Små",
    LayoutOptionAll: "Allt",
    LayoutOptionSquare: "Fyrkant",
    LayoutOptionTall: "Lång",
    LayoutOptionWide: "Bred",
    LicenseOptionAll: "Allt",
    LicenseOptionAny: "Endast kreativa Commons",
    RecentDocumentsHeader: "Nya dokument",
    Loading: "Läser in...",
    NoRecentFiles: "Inga senaste filer",
    NoRecentFilesDescription: "Försök välja en fil från din webbplats, eller ladda upp en från din enhet.",
    EditedByNamePlate: "redigerad av ",
    LinkHeader: "Från en länk",
    LinkFileInstructions: "Klistra in en länk till en fil i Onedrive för Business eller SharePoint Online",
    NoExternalLinksValidationMessage: "Vi stöder bara att koppla till filer i din egen organisation.",
    ProvidedValueIsInvalid: "Tillhandahållet värde är ogiltigt",
    ImageAriaLabelTemplate: ". {0} bild",
    DocumentLabelTemplate: "{0}, dokument, modifierad {1}, redigerad av {2}, privat",
    ODPhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/itemtypes/16_2x/photo.png",
    FolderLabelTemplate: "{0}, mapp, modifierad {1}, redigerad av {2}, {3} objekt, privat",
    FolderBackPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_backplate.svg",
    FolderFrontPlate: "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/foldericons/folder-large_frontplate_nopreview.svg",
    EmptyFileSize: "0 bytes",
    SizeUnit: [
      "bytes",
      "KB",
      "MB",
      "GB",
      "TB",
      "PB",
      "EB",
      "ZB",
      "YB"
    ],
    FilePickerHeader: "File picker",
    OrgAssetsTabLabel: "Bilder och filer som tillhandahålls av din organisation",
    RecentLinkLabel: "Nyligen",
    SiteLinkLabel: "Webbplats",
    UploadLinkLabel: "Ladda upp",
    FromLinkLinkLabel: "Från en länk",
    TypeAriaLabel: "Kolumnoperationer för filtyp, tryck på för att sortera på filtyp",
    FolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20/folder.svg",
    PhotoIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-11_20190116.001/odsp-media/images/itemtypes/20_2x/photo.png",
    FolderAltText: "Mapp",
    ImageAltText: ". {0} bild",
    NameField: "Namn",
    SortedAscending: "Sorterade a till z",
    SortedDescending: "Sorterat z till en",
    ModifiedField: "Datum ändrat",
    ModifiedByField: "Modifierad av",
    FileSizeField: "Filstorlek",
    OneDriveEmptyFolderAlt: "Tom mapp",
    OneDriveEmptyFolderDescription: "För att lägga till filer, gå till din OneDive. Du kan också lägga till filer i den här mappen med hjälp av Onedrive-appen för din dator.",
    OneDriveEmptyFolderIconUrl: "https://spoprod-a.akamaihd.net/files/odsp-next-prod_2019-01-18_20190124.001/odsp-media/images/emptyfolder/empty_folder.svg",
    OneDriveEmptyFolderTitle: "Denna mapp är tom",
    ListLayoutAriaLabel: "Visa alternativ. {0} {1}.",
    ListLayoutCompact: "Kompakt vy",
    ListLayoutCompactDescription: "Visa objekt och detaljer i en kompakt lista",
    ListLayoutList: "Listvy",
    ListLayoutListDescription: "Visa objekt och detaljer i en lista",
    ListLayoutTile: "Kakelvisning",
    ListLayoutTileDescription: "Visa objekt med kakelförhandsgranskningar",
    ListOptionsAlt: "Visa alternativ. {0} vald.",
    ListOptionsTitle: "Öppna menyn Visa alternativ",
    Selected: "vald",
    CategoryTranslationNotAvailable: "En översättning av den valda delkategorin är inte tillgänglig för detta språk.",
    Abandoned: "Övergiven",
    AbandonedPlaylist: "Spellistor",
    RemoveLanguageLabel: "Ta bort språk",
    PropertyPaneNone: "ingen",
    WebPartModeFull: "full",
    WebPartModeContentOnly: "Endast innehåll",
    PropertyPaneFilterCategory: "Kategori",
    PropertyPaneFilterSubCategory: "Underkategori",
    PropertyPaneFilterPlaylist: "Spellista",
    AdminSavingNotification: "Sparande..",
    DataUpgradeReview: "Recension",
    DataUpgradeMultilingual: "Flerspråkigt stöd är aktiverat för inlärningsvägar. Granska språken som är aktiverade för din webbplats och stäng av de språk du inte vill stödja.",
    M365Title: "Microsoft 365 Learning Pathways",
    ValidateBase: "Basadressen för CDN måste sluta i en (/).",
    CustomizeSort: "Skräddarsy sort",
    ResetSort: "Återställ sort"
  };
});